version: '3.8'

services:
  mysql-db:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ''
    ports:
      - '3307:3306'

  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: devops-docker
    depends_on:
      - mysql-db
    ports:
      - '8181:8181'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-db:3306/databasename'
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
